### signup
PUT http://localhost:3003/signup
Content-Type: application/json

{
    "name": "Beltrano",
    "email": "beltrano@gmail.com",
	"password": "123456",
    "role": "NORMAL"
}

### Login
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "sicrano@gmail.com",
	"password": "123456"
}

### GetAllUsers
GET http://localhost:3003/user/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2NGNhMWIyLTAxYTUtNDQ2OS05YWE5LTU3YzcwYTc1ZGI2OCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTIyMDkyMzIsImV4cCI6MTYxMjIwOTI5Mn0.gtzDSswgMVloQtS95Zda8w-mBJo5cb1hu5iXhQfk89E
