### postUser
POST http://localhost:3003/signup
Content-Type: application/json

{
    "email": "ciclano8@email.com",
	"password": "123456"
}

### getUserAndLogin
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "ciclano8@email.com",
	"password": "123456"
}

### getProfile
GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3MDA1NTEwLTE2MjUtNDZmYi05NzdiLWM2MTcyYjA4NWMwNiIsImlhdCI6MTYxMTY4MzI4NSwiZXhwIjoxNjExNjgzMzQ1fQ.UA285Z7tVnR7KTUAFhxwN0VJrSZ3BOlrSPCu0_k-8RI