### postUser (Signup)
POST http://localhost:3003/signup
Content-Type: application/json

{
    "name": "Sicrano",
    "email": "sicrano@gmail.com",
	"password": "123456",
    "role": "NORMAL"
}

### getUserAndLogin (Login)
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "ciclano@email.com",
	"password": "90f91267"
}

### getProfile (Pegar próprio perfil)
GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUyYjI0ZWYyLTQ2YjYtNGEwMi05OTA2LTYxNmQzY2UwYjM5MCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE4NTMwNjYsImV4cCI6MTYxMTg1MzM2Nn0.VdIvwCrys2QZY7B-R98-6zciC5-wb3m7bNi3OV5ORX8

### getUserProfile (Pegar perfil de outro usuário)
GET http://localhost:3003/user/4743d95c-d644-488e-b9dd-58149777d8b9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUyYjI0ZWYyLTQ2YjYtNGEwMi05OTA2LTYxNmQzY2UwYjM5MCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE4NTMwNjYsImV4cCI6MTYxMTg1MzM2Nn0.VdIvwCrys2QZY7B-R98-6zciC5-wb3m7bNi3OV5ORX8

### createRecipe (Criar receita)
POST http://localhost:3003/recipe
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjExMGVhZmE3LTlmYjctNDcwYi1hMDA0LTBjNGQ0OTk2ZjI4NyIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE5NjEzNDUsImV4cCI6MTYxMTk2MTY0NX0.jxRKAAA_P2WiLC_VkQRAGMmKWKGVSVALgI3Vt3wIPWI
Content-Type: application/json

{
    "title": "Receita de comida",
	"description": "Modo de preparo"
}

### getRecipe (Pegar receita)
GET http://localhost:3003/recipe/f18551da-e5cf-40b9-9888-8ed01de48fd1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUyYjI0ZWYyLTQ2YjYtNGEwMi05OTA2LTYxNmQzY2UwYjM5MCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE4NTg2NjUsImV4cCI6MTYxMTg1ODk2NX0.B7b2z2C7DLssTZCCrxSsci55rWRwdk5bElfinhoNtGI

### followUser (Seguir usuário)
POST http://localhost:3003/user/follow
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUyYjI0ZWYyLTQ2YjYtNGEwMi05OTA2LTYxNmQzY2UwYjM5MCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE5NjE1ODIsImV4cCI6MTYxMTk2MTg4Mn0.m5ua73ju-t5nbWOFPPWtfGc-N5goLGnbekyPbjKHDac
Content-Type: application/json

{
    "userToFollowId": "110eafa7-9fb7-470b-a004-0c4d4996f287"
}

### unfollowUser (Deixar de seguir usuário)
POST http://localhost:3003/user/unfollow
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3NDNkOTVjLWQ2NDQtNDg4ZS1iOWRkLTU4MTQ5Nzc3ZDhiOSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE4NzM4NzYsImV4cCI6MTYxMTg3NDE3Nn0.Y3FBM0dpn_vFV9xmEsaocyKnWGAhBmECWk3UBWpsGgs
Content-Type: application/json

{
    "userToUnfollowId": "b005ed32-b147-4e3f-bf6b-7b7b1f5c5fed"
}

### getFeed (Pegar feed de receitas)
GET http://localhost:3003/user/feed
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNjMTFjNzQzLWE1MDMtNDhiYy05YTM2LTM2MTNmOWJlZmI1YyIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE5NjE4MjEsImV4cCI6MTYxMTk2MjEyMX0.7Sz4OUPNaCaajrDcAs53RkyM9zXDNkqlCGc6XZuWEFk

### editRecipe (Editar receita)
PUT http://localhost:3003/recipe/edit/feb0e930-3b5d-4280-a225-0bac9bf2c8b5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIwMDVlZDMyLWIxNDctNGUzZi1iZjZiLTdiN2IxZjVjNWZlZCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE5NDUzMzEsImV4cCI6MTYxMTk0NTYzMX0.KzHqdKye-4_-hWEDeYJ1_sYybyY_NThKuxUwkyGbno8
Content-Type: application/json

{
    "title": "Receita de macarrão ao pesto",
	"description": "Modo de preparo"
}

### deleteRecipe (Deletar receita)
DELETE http://localhost:3003/recipe/delete/63315c9a-4b5d-4a17-97b4-237ade8469c9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUyYjI0ZWYyLTQ2YjYtNGEwMi05OTA2LTYxNmQzY2UwYjM5MCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE5NDYyODAsImV4cCI6MTYxMTk0NjU4MH0.qHDEDEp0KNua3yn1pChGqAQB_ivzGy8m4RKxWCzd3GE

### deleteProfile (Deletar conta)
DELETE http://localhost:3003/user/0b2d605c-8bd7-49e1-9107-049d4d3251d7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiMmQ2MDVjLThiZDctNDllMS05MTA3LTA0OWQ0ZDMyNTFkNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYxMTk2NDE1OSwiZXhwIjoxNjExOTY0NDU5fQ.Q-FWdT3qlsy4crFvnhhoRrrfME52qBYFZBldcdkvcR8

### resetPassword (Esqueci a senha)
POST http://localhost:3003/user/reset/password
Content-Type: application/json

{
    "email": "ciclano@email.com"
}