### postUser (Signup)
POST http://localhost:3003/signup
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@email.com",
	"password": "123456",
    "role": "ADMIN"
}

### getUserAndLogin (Login)
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "ciclano@email.com",
	"password": "123456"
}

### getProfile (Pegar próprio perfil)
GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUyYjI0ZWYyLTQ2YjYtNGEwMi05OTA2LTYxNmQzY2UwYjM5MCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE4NTMwNjYsImV4cCI6MTYxMTg1MzM2Nn0.VdIvwCrys2QZY7B-R98-6zciC5-wb3m7bNi3OV5ORX8

### getUserProfile (Pegar perfil de outro usuário)
GET http://localhost:3003/user/4743d95c-d644-488e-b9dd-58149777d8b9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUyYjI0ZWYyLTQ2YjYtNGEwMi05OTA2LTYxNmQzY2UwYjM5MCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE4NTMwNjYsImV4cCI6MTYxMTg1MzM2Nn0.VdIvwCrys2QZY7B-R98-6zciC5-wb3m7bNi3OV5ORX8

### createRecipe (Criar receita)
POST http://localhost:3003/recipe
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3NDNkOTVjLWQ2NDQtNDg4ZS1iOWRkLTU4MTQ5Nzc3ZDhiOSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE4ODAxMDYsImV4cCI6MTYxMTg4MDQwNn0.0V1c4OJosghU7C5gODoXPjIuWdBXoKpw9bI8qv4N_ac
Content-Type: application/json

{
    "title": "Receita de torta",
	"description": "Modo de preparo"
}

### getRecipe (Pegar receita)
GET http://localhost:3003/recipe/f18551da-e5cf-40b9-9888-8ed01de48fd1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUyYjI0ZWYyLTQ2YjYtNGEwMi05OTA2LTYxNmQzY2UwYjM5MCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE4NTg2NjUsImV4cCI6MTYxMTg1ODk2NX0.B7b2z2C7DLssTZCCrxSsci55rWRwdk5bElfinhoNtGI

### followUser (Seguir usuário)
POST http://localhost:3003/user/follow
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3NDNkOTVjLWQ2NDQtNDg4ZS1iOWRkLTU4MTQ5Nzc3ZDhiOSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE4NzMxNTEsImV4cCI6MTYxMTg3MzQ1MX0.KuWbV0KLif0LZjFr6ZC1ni-NqoKZsPWx3vF47EhykVQ
Content-Type: application/json

{
    "userToFollowId": "b005ed32-b147-4e3f-bf6b-7b7b1f5c5fed"
}

### unfollowUser (Deixar de seguir usuário)
POST http://localhost:3003/user/unfollow
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3NDNkOTVjLWQ2NDQtNDg4ZS1iOWRkLTU4MTQ5Nzc3ZDhiOSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE4NzM4NzYsImV4cCI6MTYxMTg3NDE3Nn0.Y3FBM0dpn_vFV9xmEsaocyKnWGAhBmECWk3UBWpsGgs
Content-Type: application/json

{
    "userToUnfollowId": "b005ed32-b147-4e3f-bf6b-7b7b1f5c5fed"
}

### getFeed (Pegar feed de receitas)
GET http://localhost:3003/user/feed
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUyYjI0ZWYyLTQ2YjYtNGEwMi05OTA2LTYxNmQzY2UwYjM5MCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE5MzY4ODksImV4cCI6MTYxMTkzNzE4OX0.zMLRYaIjxrWPuZY6FqFMazgJJJi4gRlVbieoSGUgfpQ

### editRecipe (Editar receita)
PUT http://localhost:3003/recipe/edit/feb0e930-3b5d-4280-a225-0bac9bf2c8b5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIwMDVlZDMyLWIxNDctNGUzZi1iZjZiLTdiN2IxZjVjNWZlZCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE5NDUzMzEsImV4cCI6MTYxMTk0NTYzMX0.KzHqdKye-4_-hWEDeYJ1_sYybyY_NThKuxUwkyGbno8
Content-Type: application/json

{
    "title": "Receita de macarrão ao pesto",
	"description": "Modo de preparo"
}

### editRecipe (Editar receita)
DELETE http://localhost:3003/recipe/delete/63315c9a-4b5d-4a17-97b4-237ade8469c9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUyYjI0ZWYyLTQ2YjYtNGEwMi05OTA2LTYxNmQzY2UwYjM5MCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MTE5NDYyODAsImV4cCI6MTYxMTk0NjU4MH0.qHDEDEp0KNua3yn1pChGqAQB_ivzGy8m4RKxWCzd3GE