### postUser
POST http://localhost:3003/signup
Content-Type: application/json

{
    "email": "ciclano7@email.com",
	"password": "123456"
}

### getUserAndLogin
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "ciclano5@email.com",
	"password": "123456"
}

### getProfile
GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNlMDBjZDIyLTI2YTItNGQ5ZS04YmYyLTlkZTM2YmIwZjkzYSIsImlhdCI6MTYxMTYwNzE0MSwiZXhwIjoxNjExNjA3MjAxfQ.OKWNvtgvZyRYDu2qlKYryg7wm35bMb8oUaTDc6FLboc