### signup
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Ciclano",
    "nickname": "Ci",
    "email": "ciclano@gmail.com",
	"password": "123456",
    "role": "NORMAL"
}

### Login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
	"password": "123456"
}

### createTask
PUT http://localhost:3003/task
Content-Type: application/json

{
    "title": "Tarefa 1",
	"description": "alguma coisa",
    "deadline": "2021-02-30",
	"authorId": "a907bde2-a70f-4c96-82c3-9ea3cdffbbb2"
}

### getTaskById
GET http://localhost:3003/task/b35b9a3c-96a0-445d-b9ff-929e6638b5fc